const {test}=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {Runner}=require('../lib/runner');const {validateFlow}=require('../lib/flow');const {migrate}=require('../lib/migration');
test('flow rejects unbounded loops and unavailable branch variables; migration blocks arbitrary scripts',()=>{
  const config=require('../lib/config').validate({schemaVersion:4,singleRun:true,scenario:{steps:[{method:'GET',url:'http://localhost'}]},stages:'1:1'});assert.ok(parseInt(require('../lib/k6').options(config).scenarios.main.maxDuration)>60,'a functional flow without a deadline must not have an implicit one-minute cap');
  assert.throws(()=>validateFlow({steps:[{type:'loop',mode:'count',children:[]}]}),/limite/);
  const m=migrate({collection:{info:{name:'old'},item:[{name:'x',request:{method:'GET',url:'http://localhost'},event:[{listen:'test',script:{exec:['pm.sendRequest("http://localhost");']}}]}]}});assert.equal(m.compatible,false);assert.match(m.issues[0].message,/Script/);
});
test('k6 authenticates, extracts typed data, loops details and regenerates identical XLSX',async t=>{
  const hits=[];const server=http.createServer((req,res)=>{hits.push([req.url,req.headers.authorization]);res.setHeader('Content-Type','application/json');if(req.url==='/login')res.end(JSON.stringify({token:'SECRET-TOKEN',items:[{id:1},{id:2}]}));else res.end(JSON.stringify({ok:true}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'stress-flow-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const base=`http://127.0.0.1:${server.address().port}`;
  const runner=new Runner({schemaVersion:4,mode:'builder',singleRun:true,scenario:{variables:[{key:'BASE_URL',value:base}],steps:[{name:'Login',method:'GET',url:'{{BASE_URL}}/login',extracts:[{source:'json',path:'token',variable:'TOKEN',secret:true},{source:'json',path:'items',variable:'ITEMS'}]},{type:'loop',name:'Detalhes',mode:'items',variable:'ITEMS',limit:10,children:[{name:'Detail',method:'GET',url:'{{BASE_URL}}/detail',headers:[{key:'Authorization',value:'Bearer {{TOKEN}}'}],checks:[{source:'json',path:'ok',operator:'equals',value:true}]}]}]},stages:'1:1',evidence:{minResponses:1,minLoadPercent:0}},path.join(dir,'flow.xlsx'));
  const result=await runner.start();assert.equal(result.requests,3,JSON.stringify(result));assert.equal(hits.length,3);assert.equal(hits[1][1],'Bearer SECRET-TOKEN');assert.equal(result.passed,true,JSON.stringify(result));assert.equal(result.methodologyVersion,'4.0');assert.equal(result.reportInfo.integrity,true);assert.equal(result.reportStatus,'ready');
  const archive=require('node:zlib').gunzipSync(fs.readFileSync(runner.eventsPath+'.gz')).toString();assert.equal(archive.includes('SECRET-TOKEN'),false);assert.ok(archive.includes('stepEnd'));
});
async function local(t,handler){const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();return new Promise(r=>server.close(r));});return `http://127.0.0.1:${server.address().port}`;}
test('branches, typed templates, data rows, redirects and skipped paths have exact counts',async t=>{
  const seen=[];const url=await local(t,async(req,res)=>{let body='';for await(const c of req)body+=c;seen.push({url:req.url,body});if(req.url==='/redirect'){res.writeHead(302,{Location:'/final'});res.end();}else res.end('{"ok":true}');});
  const runner=new Runner({schemaVersion:4,singleRun:true,stages:'1:1',scenario:{variables:[{key:'FLAG',value:'yes'}],dataset:{select:'iteration',exhaustion:'error',rows:[{TEXT:'a"b c\\d',ID:42}]},steps:[{id:'branch',type:'condition',condition:{variable:'FLAG',operator:'equals',value:'yes'},then:[{id:'typed',method:'POST',url:url+'/typed',bodyType:'json',body:'{"id":{{ID}},"text":"prefix {{TEXT}} suffix"}',checks:[{source:'status',operator:'equals',value:200}]}],else:[{id:'unused',method:'GET',url:url+'/unused'}]},{id:'redirect',method:'GET',url:url+'/redirect',checks:[{source:'status',operator:'equals',value:200}]}]}});
  const result=await runner.start();assert.equal(result.passed,true,JSON.stringify(result));assert.equal(result.requests,3);assert.equal(seen.length,3);assert.deepEqual(JSON.parse(seen[0].body),{id:42,text:'prefix a"b c\\d suffix'});assert.equal(seen[2].url,'/final');assert.equal(result.steps.find(s=>s.nodeId==='unused').skipped,1);
});
test('per-user preparation isolates sessions and runs only once per virtual user',async t=>{
  let logins=0,details=0;const tokens=new Set();const url=await local(t,(req,res)=>{if(req.url==='/login'){const token='token-'+(++logins);tokens.add(token);res.end(JSON.stringify({token}));}else{if(tokens.has(req.headers.authorization))details++;else res.statusCode=401;setTimeout(()=>res.end('{}'),10);}});
  const runner=new Runner({schemaVersion:4,stages:'1:2',evidence:{minResponses:1,minLoadPercent:0},scenario:{perUser:[{id:'login',method:'GET',url:url+'/login',extracts:[{source:'json',path:'token',variable:'TOKEN',scope:'session',secret:true}]}],steps:[{id:'detail',method:'GET',url:url+'/detail',headers:[{key:'Authorization',value:'{{TOKEN}}'}]}]}});
  const result=await runner.start();assert.equal(logins,2);assert.ok(details>2);assert.equal(result.requests,logins+details);assert.equal(result.failedRuns,0);assert.equal(result.passed,true,JSON.stringify(result));
});
test('failed HTTP or required extraction fails the journey and skips downstream requests',async t=>{
  let count=0;const url=await local(t,(_req,res)=>{count++;res.end('{}');});const result=await new Runner({schemaVersion:4,singleRun:true,stages:'1:1',scenario:{steps:[{id:'missing',method:'GET',url,extracts:[{source:'json',path:'missing',variable:'TOKEN'}]},{id:'next',method:'GET',url,headers:[{key:'Authorization',value:'{{TOKEN}}'}]}]}}).start();assert.equal(count,1);assert.equal(result.failedRuns,1);assert.equal(result.passed,false);assert.equal(result.evaluation.verdict,'rejected');assert.equal(result.steps.find(s=>s.nodeId==='next').skipped,1);
});
test('native setup and teardown are recorded but excluded from performance samples',async t=>{
  const url=await local(t,(_req,res)=>res.end('{"id":123}'));const result=await new Runner({schemaVersion:4,singleRun:true,stages:'1:1',scenario:{setup:[{id:'prepare',method:'GET',url,extracts:[{source:'json',path:'id',variable:'ID'}]}],steps:[{id:'work',method:'GET',url:url+'/{{ID}}'}],teardown:[{id:'clean',method:'DELETE',url:url+'/{{ID}}'}]}}).start();assert.equal(result.requests,3);assert.equal(result.performance.requests,1);assert.equal(result.passed,true,JSON.stringify(result));
});
test('a full response URL can drive the next request without a fixed base URL',async t=>{
  const paths=[];const url=await local(t,(req,res)=>{paths.push(req.url);res.setHeader('Content-Type','application/json');res.end(req.url==='/start'?JSON.stringify({next:'http://'+req.headers.host+'/detail/42'}):'{}');});
  const result=await new Runner({schemaVersion:4,singleRun:true,stages:'1:1',scenario:{steps:[{id:'start',method:'GET',url:url+'/start',extracts:[{source:'json',path:'next',variable:'DETAIL_URL'}]},{id:'next',method:'GET',url:'{{DETAIL_URL}}'}]}}).start();assert.equal(result.passed,true,JSON.stringify(result));assert.deepEqual(paths,['/start','/detail/42']);
});
test('pauses between journeys do not extend a finished load stage or alter completion integrity',async t=>{
  const url=await local(t,(_req,res)=>res.end('ok'));const start=Date.now();const result=await new Runner({schemaVersion:4,stages:'1:1',thinkTime:60000,evidence:{minResponses:1,minLoadPercent:0},scenario:{steps:[{id:'health',method:'GET',url}]}}).start();assert.ok(Date.now()-start<5000);assert.equal(result.passed,true,JSON.stringify(result));assert.equal(result.k6Counters.journeys,result.runs);assert.ok(result.requests>=1);
});
