const { parentPort, workerData } = require('node:worker_threads')
const { buildReport } = require('./workbook')
buildReport(workerData)
  .then((result) => parentPort.postMessage(result))
  .catch((error) => parentPort.postMessage({ error: error.message }))
